### ISSUE TITLE
Use Github-Pages

### ISSUE THREAD

**Issue by BlackIQ** [Amirmahdi-Kaheh/LoginPage-FA-#2]
Use Github-Pages to make your project visible for people. In this case people can visit your project online.

Go to your repository -> Go to settings -> Go to pages in left side or settings -> Choose branch and choose root directory.

After that, you can use via [this link](Amirmahdi-Kaheh.github.io/LoginPage-FA-).

Simple.

**Comment by Amirmahdi-Kaheh** [comment]
سلام حاجی خبری ازت نیست هر چیم بهت پیام دادم ندیدی 
حالت چطوره ؟

نگاه من اینایی که گفتی رو اجرا کردم ولی خب صفحه ریدمی رو میاره رو سرور چکار کنم صفحه ایندکس رو بیاره بالا ؟

**Comment by amirghazi87** [comment]
سلام در #4 درستش کردم

**Comment by BlackIQ** [comment]
@Amirmahdi-Kaheh.
مرج کن درست میشه.

**Comment by Amirmahdi-Kaheh** [comment]
دمتون گرم ♥♥♥
